export enum PermissionEnum {
  // User permission
  UPDATE_USER = 'UPDATE_USER',
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
}
